// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise"
import { OpenAPI } from "./core/OpenAPI"
import { request as __request } from "./core/request"
import type {
  AasListTemplatesResponse,
  AasListAllAasResponse,
  AasCreateAasData,
  AasCreateAasResponse,
  AasUpdateAasMetadataData,
  AasUpdateAasMetadataResponse,
  AasAttachSubmodelsData,
  AasAttachSubmodelsResponse,
  AasRemoveSubmodelData,
  AasRemoveSubmodelResponse,
  AasUpdateSubmodelDataData,
  AasUpdateSubmodelDataResponse,
  AasDeleteAasData,
  AasDeleteAasResponse,
  AasGetAasData,
  AasGetAasResponse,
  DppListDppSectionsData,
  DppListDppSectionsResponse,
  DppGetDppSectionData,
  DppGetDppSectionResponse,
  DppDownloadCompleteDppData,
  DppDownloadCompleteDppResponse,
  LoginLoginAccessTokenData,
  LoginLoginAccessTokenResponse,
  LoginTestTokenResponse,
  LoginRecoverPasswordData,
  LoginRecoverPasswordResponse,
  LoginResetPasswordData,
  LoginResetPasswordResponse,
  LoginRecoverPasswordHtmlContentData,
  LoginRecoverPasswordHtmlContentResponse,
  PrivateCreateUserData,
  PrivateCreateUserResponse,
  UsersReadUsersData,
  UsersReadUsersResponse,
  UsersCreateUserData,
  UsersCreateUserResponse,
  UsersReadUserMeResponse,
  UsersDeleteUserMeResponse,
  UsersUpdateUserMeData,
  UsersUpdateUserMeResponse,
  UsersUpdatePasswordMeData,
  UsersUpdatePasswordMeResponse,
  UsersRegisterUserData,
  UsersRegisterUserResponse,
  UsersReadUserByIdData,
  UsersReadUserByIdResponse,
  UsersUpdateUserData,
  UsersUpdateUserResponse,
  UsersDeleteUserData,
  UsersDeleteUserResponse,
  UtilsTestEmailData,
  UtilsTestEmailResponse,
  UtilsHealthCheckResponse,
} from "./types.gen"

export class AasService {
  /**
   * List available AASX template packages
   * Return a list of available AASX template packages.
   * This endpoint is available only to superusers.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static listTemplates(): CancelablePromise<AasListTemplatesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/aas/templates",
    })
  }

  /**
   * List all AAS instances
   * Return a list of all stored AAS assets (each asset is returned as raw AAS JSON).
   * Accessible to all authenticated users.
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static listAllAas(): CancelablePromise<AasListAllAasResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/aas/",
    })
  }

  /**
   * Create a new AAS from selected submodel templates
   * Create a new AAS instance by attaching one or more submodel templates.
   * - **template_ids**: A list of template identifiers (as defined in the template metadata) to attach.
   * - **asset_data**: Optional additional asset metadata (e.g. global asset id, display name, description).
   * This endpoint is restricted to superusers.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static createAas(
    data: AasCreateAasData,
  ): CancelablePromise<AasCreateAasResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/aas/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update metadata on an AAS instance
   * Update metadata on an AAS instance
   * @param data The data for the request.
   * @param data.aasId
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static updateAasMetadata(
    data: AasUpdateAasMetadataData,
  ): CancelablePromise<AasUpdateAasMetadataResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/aas/{aas_id}/metadata",
      path: {
        aas_id: data.aasId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Attach new submodel(s) to an existing AAS asset
   * Attach new submodel instance(s) (derived from the provided template IDs) to the specified AAS asset.
   * This endpoint is restricted to superusers.
   * @param data The data for the request.
   * @param data.aasId
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static attachSubmodels(
    data: AasAttachSubmodelsData,
  ): CancelablePromise<AasAttachSubmodelsResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/aas/{aas_id}/submodels/attach",
      path: {
        aas_id: data.aasId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Remove a submodel from an AAS
   * Remove a specific submodel (by its ID) from an existing AAS.
   * @param data The data for the request.
   * @param data.aasId
   * @param data.submodelId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static removeSubmodel(
    data: AasRemoveSubmodelData,
  ): CancelablePromise<AasRemoveSubmodelResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/aas/{aas_id}/submodels/{submodel_id}",
      path: {
        aas_id: data.aasId,
        submodel_id: data.submodelId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update data on a submodel instance for a given AAS
   * Update data on a specific submodel instance (e.g. property values or dynamic data) for a given AAS.
   * @param data The data for the request.
   * @param data.aasId
   * @param data.submodelId
   * @param data.requestBody
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static updateSubmodelData(
    data: AasUpdateSubmodelDataData,
  ): CancelablePromise<AasUpdateSubmodelDataResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/aas/{aas_id}/submodels/{submodel_id}",
      path: {
        aas_id: data.aasId,
        submodel_id: data.submodelId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete an AAS instance (cascade deletion of submodels)
   * Delete an AAS asset and all its associated submodels.
   * This endpoint is restricted to admins.
   * @param data The data for the request.
   * @param data.aasId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static deleteAas(
    data: AasDeleteAasData,
  ): CancelablePromise<AasDeleteAasResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/aas/{aas_id}",
      path: {
        aas_id: data.aasId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Retrieve a specific AAS instance by ID
   * Retrieve a single AAS instance by its unique identifier.
   * @param data The data for the request.
   * @param data.aasId
   * @returns unknown Successful Response
   * @throws ApiError
   */
  public static getAas(
    data: AasGetAasData,
  ): CancelablePromise<AasGetAasResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/aas/{aas_id}",
      path: {
        aas_id: data.aasId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class DppService {
  /**
   * List available DPP sections
   * Get available DPP sections and their metadata.
   *
   * Args:
   * aas_id: ID of the AAS to generate DPP for
   * status_filter: Optional filter for section status
   * session: Database session dependency
   *
   * Returns:
   * List of available DPP sections with their status
   * @param data The data for the request.
   * @param data.aasId ID of the AAS to generate DPP for
   * @param data.statusFilter Filter sections by status (available, incomplete)
   * @returns DPPSectionInfo List of available DPP sections with their status
   * @throws ApiError
   */
  public static listDppSections(
    data: DppListDppSectionsData,
  ): CancelablePromise<DppListDppSectionsResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/dpp/{aas_id}/sections",
      path: {
        aas_id: data.aasId,
      },
      query: {
        status_filter: data.statusFilter,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get DPP section content
   * Get detailed content for a specific DPP section.
   *
   * Args:
   * aas_id: ID of the AAS
   * section_id: ID of the section to retrieve
   * include_raw: Whether to include raw data in the response
   * session: Database session dependency
   *
   * Returns:
   * Detailed content of the requested DPP section
   * @param data The data for the request.
   * @param data.aasId ID of the AAS
   * @param data.sectionId ID of the section to retrieve
   * @param data.includeRaw Whether to include raw data in the response
   * @returns DPPSection Detailed content of the requested DPP section
   * @throws ApiError
   */
  public static getDppSection(
    data: DppGetDppSectionData,
  ): CancelablePromise<DppGetDppSectionResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/dpp/{aas_id}/section/{section_id}",
      path: {
        aas_id: data.aasId,
        section_id: data.sectionId,
      },
      query: {
        include_raw: data.includeRaw,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Download complete DPP in JSON format
   * Download complete DPP in JSON format.
   *
   * Args:
   * aas_id: ID of the AAS to generate DPP for
   * include_raw: Whether to include raw data in the output
   * session: Database session dependency
   *
   * Returns:
   * Complete DPP document with all available sections
   * @param data The data for the request.
   * @param data.aasId ID of the AAS to generate DPP for
   * @param data.includeRaw Whether to include raw data in the output
   * @returns CompleteDPP Complete DPP document with all available sections
   * @throws ApiError
   */
  public static downloadCompleteDpp(
    data: DppDownloadCompleteDppData,
  ): CancelablePromise<DppDownloadCompleteDppResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/dpp/{aas_id}/download",
      path: {
        aas_id: data.aasId,
      },
      query: {
        include_raw: data.includeRaw,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class LoginService {
  /**
   * Login Access Token
   * OAuth2 compatible token login, get an access token for future requests
   * @param data The data for the request.
   * @param data.formData
   * @returns Token Successful Response
   * @throws ApiError
   */
  public static loginAccessToken(
    data: LoginLoginAccessTokenData,
  ): CancelablePromise<LoginLoginAccessTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/access-token",
      formData: data.formData,
      mediaType: "application/x-www-form-urlencoded",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Test Token
   * Test access token
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static testToken(): CancelablePromise<LoginTestTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/test-token",
    })
  }

  /**
   * Recover Password
   * Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static recoverPassword(
    data: LoginRecoverPasswordData,
  ): CancelablePromise<LoginRecoverPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Reset Password
   * Reset password
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static resetPassword(
    data: LoginResetPasswordData,
  ): CancelablePromise<LoginResetPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/reset-password/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Recover Password Html Content
   * HTML Content for Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns string Successful Response
   * @throws ApiError
   */
  public static recoverPasswordHtmlContent(
    data: LoginRecoverPasswordHtmlContentData,
  ): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery-html-content/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class PrivateService {
  /**
   * Create User
   * Create a new user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: PrivateCreateUserData,
  ): CancelablePromise<PrivateCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/private/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UsersService {
  /**
   * Read Users
   * Retrieve users.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns UsersPublic Successful Response
   * @throws ApiError
   */
  public static readUsers(
    data: UsersReadUsersData = {},
  ): CancelablePromise<UsersReadUsersResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create User
   * Create new user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: UsersCreateUserData,
  ): CancelablePromise<UsersCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User Me
   * Get current user.
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Delete User Me
   * Delete own user.
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Update User Me
   * Update own user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUserMe(
    data: UsersUpdateUserMeData,
  ): CancelablePromise<UsersUpdateUserMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Password Me
   * Update own password.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static updatePasswordMe(
    data: UsersUpdatePasswordMeData,
  ): CancelablePromise<UsersUpdatePasswordMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me/password",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Register User
   * Create new user without the need to be logged in.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static registerUser(
    data: UsersRegisterUserData,
  ): CancelablePromise<UsersRegisterUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/signup",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User By Id
   * Get a specific user by id.
   * @param data The data for the request.
   * @param data.userId
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserById(
    data: UsersReadUserByIdData,
  ): CancelablePromise<UsersReadUserByIdResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update User
   * Update a user.
   * @param data The data for the request.
   * @param data.userId
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUser(
    data: UsersUpdateUserData,
  ): CancelablePromise<UsersUpdateUserResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete User
   * Delete a user.
   * @param data The data for the request.
   * @param data.userId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUser(
    data: UsersDeleteUserData,
  ): CancelablePromise<UsersDeleteUserResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UtilsService {
  /**
   * Test Email
   * Test emails.
   * @param data The data for the request.
   * @param data.emailTo
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static testEmail(
    data: UtilsTestEmailData,
  ): CancelablePromise<UtilsTestEmailResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/utils/test-email/",
      query: {
        email_to: data.emailTo,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Health Check
   * @returns boolean Successful Response
   * @throws ApiError
   */
  public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/utils/health-check/",
    })
  }
}
