"""Add AAS submodel table with a JSONB column

Revision ID: ca33e68b38f9
Revises: 4cdb0b53fdc0
Create Date: 2025-02-13 15:39:01.238285

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca33e68b38f9'
down_revision = '4cdb0b53fdc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aas_submodel',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aas_submodel_id'), 'aas_submodel', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aas_submodel_id'), table_name='aas_submodel')
    op.drop_table('aas_submodel')
    # ### end Alembic commands ###
